from pr_pro.exercise import PowerExercise, RepsAndWeightsExercise, RepsExercise

arms = RepsExercise(name='Arms ...')

box_jump = RepsExercise(name='Box jump')
pogo_jump = RepsExercise(name='Pogo jump')
hurdle_jumps_to_box = RepsExercise(name='Hurdle jumps to box')
eurostep_to_land = RepsExercise(name='Eurostep to land')
eurostep_to_box = RepsExercise(name='Eurostep to box')
reverse_hyperextension = RepsExercise(name='Reverse hyperextension')
side_plank_leg_raise = RepsExercise(name='Side plank leg raise')
hanging_leg_raise = RepsExercise(name='Hanging leg raise')
banded_toes_to_bar = RepsExercise(name='Banded toes to bar')
trx_row = RepsExercise(name='TRX row')

snatch = PowerExercise(name='Snatch')
muscle_snatch = PowerExercise(name='Muscle snatch')
power_snatch = PowerExercise(name='Power snatch')
low_hang_power_snatch = PowerExercise(name='Low hang power snatch')
snatch_high_pull = PowerExercise(name='Snatch high pull')
push_press = PowerExercise(name='Push press')
clean_jerk = PowerExercise(name='Clean & jerk')
jerk = PowerExercise(name='Jerk')

bo_dumbbell_row = RepsAndWeightsExercise(name='Bentover dumbbell row (single arm)')
pallof_press = RepsAndWeightsExercise(name='Pallof press')
lat_pulldown = RepsAndWeightsExercise(name='Lat pulldown')
barbell_row = RepsAndWeightsExercise(name='Bentover barbell row')
snatch_grip_btn_press = RepsAndWeightsExercise(name='Snatch grip behind the neck press')
dumbbell_press = RepsAndWeightsExercise(name='Dumbbell press')
russian_twist = RepsAndWeightsExercise(name='Russian twist')
cable_pulldown = RepsAndWeightsExercise(name='Straight arm cable pulldown')
calf_raise = RepsAndWeightsExercise(name='Calf raise')
single_leg_calf_raise = RepsAndWeightsExercise(name='Single leg calf raise')
lunges = RepsAndWeightsExercise(name='Lunges')
bulgarian_split_squats = RepsAndWeightsExercise(name='Bulgarian split squats')
weighted_pullup = RepsAndWeightsExercise(name='Weighted pullup')
